CREATE TABLE `lesson_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`unit` varchar(128),
	`lessonNumber` varchar(16),
	`academicYear` varchar(16),
	`duration` int,
	`title` varchar(255) NOT NULL,
	`yearGroup` varchar(64),
	`subject` varchar(128),
	`skills` text,
	`systems` text,
	`specificCompetences` text,
	`saberesBasicos` text,
	`learningOutcomes` text,
	`evaluationCriteria` text,
	`previousKnowledge` text,
	`materials` text,
	`spaces` text,
	`procedures` text,
	`competencies` text,
	`aiGenerated` boolean NOT NULL DEFAULT false,
	`calendarEventId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lesson_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `school_calendar_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`academicYear` varchar(16) NOT NULL,
	`eventDate` timestamp NOT NULL,
	`eventType` enum('holiday','special','exam','excursion','event','lesson','ai_generated') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`competency` varchar(16),
	`yearGroup` varchar(16),
	`subject` varchar(128),
	`aiGenerated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `school_calendar_events_id` PRIMARY KEY(`id`)
);
