/**
 * RegisterWithInvite — Teacher self-registration page.
 *
 * Accessed via /register?invite=TOKEN (link generated by a Director).
 * On mount the token is validated server-side via localAuth.verifyInviteToken.
 * The form is only shown when the token is confirmed valid; otherwise a clear
 * error screen is displayed with guidance to contact the Director.
 *
 * On submit, localAuth.register is called with the invite token so the server
 * can re-validate and mark the invite as used atomically.
 */

import { useState, useMemo, useEffect } from "react";
import { trpc } from "@/lib/trpc";
import { useI18n } from "@/contexts/I18nContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";

import {
  AlertCircle,
  CheckCircle2,
  Clock,
  Eye,
  EyeOff,
  Globe,
  Loader2,
  ShieldCheck,
  XCircle,
} from "lucide-react";

const DEFAULT_BG =
  "https://d2xsxph8kpxj0f.cloudfront.net/310419663032477713/ZdUr4NNhMJ6HJrxx9nW6jZ/hero-bg-UMuQESLM5HrV2VsrndDo2h.webp";

const LANG_OPTIONS = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
  { code: "ca", label: "Català" },
];

export default function RegisterWithInvite() {
  const { t, lang, setLang } = useI18n();
  const { data: customBg } = trpc.director.getLoginBackground.useQuery();
  const bgImage = customBg ?? DEFAULT_BG;
  const [showLangMenu, setShowLangMenu] = useState(false);
  useDocumentTitle("Registre · SEBA AI Aina");
  const { isAuthenticated, loading: authLoading } = useAuth();

  // ── Extract invite token from URL ─────────────────────────────────────────
  const inviteToken = useMemo(() => {
    try {
      return new URLSearchParams(window.location.search).get("invite") ?? "";
    } catch {
      return "";
    }
  }, []);

  // ── Redirect if already authenticated ─────────────────────────────────────
  useEffect(() => {
    if (!authLoading && isAuthenticated) {
      window.location.href = "/";
    }
  }, [authLoading, isAuthenticated]);

  // ── Server-side token verification (runs once on mount) ───────────────────
  const {
    data: tokenData,
    isLoading: tokenLoading,
    error: tokenError,
  } = trpc.localAuth.verifyInviteToken.useQuery(
    { token: inviteToken },
    {
      enabled: !!inviteToken,
      retry: false,
      refetchOnWindowFocus: false,
    }
  );

  // ── Registration form state ───────────────────────────────────────────────
  const [regEmail, setRegEmail] = useState("");
  const [regPassword, setRegPassword] = useState("");
  const [regConfirm, setRegConfirm] = useState("");
  const [regName, setRegName] = useState("");
  const [showPw, setShowPw] = useState(false);
  const [regError, setRegError] = useState("");
  const [registered, setRegistered] = useState(false);

  // Pre-fill email when the invite has one
  useEffect(() => {
    if (tokenData?.email) {
      setRegEmail(tokenData.email);
    }
  }, [tokenData]);

  const registerMutation = trpc.localAuth.register.useMutation({
    onSuccess: () => {
      setRegistered(true);
      setTimeout(() => {
        window.location.href = "/";
      }, 1500);
    },
    onError: (err) => setRegError(err.message),
  });

  const handleRegister = (e: React.FormEvent) => {
    e.preventDefault();
    setRegError("");
    if (regPassword !== regConfirm) {
      setRegError(t("local_auth_passwords_no_match"));
      return;
    }
    registerMutation.mutate({
      email: regEmail,
      password: regPassword,
      displayName: regName,
      inviteToken,
    });
  };

  // ── Derived token error type ──────────────────────────────────────────────
  type TokenErrorKind = "missing" | "invalid" | "used" | "expired" | "unknown";

  const tokenErrorKind: TokenErrorKind = useMemo(() => {
    if (!inviteToken) return "missing";
    if (!tokenError) return "unknown"; // shouldn't reach this branch
    const msg = tokenError.message ?? "";
    if (msg.toLowerCase().includes("already been used")) return "used";
    if (msg.toLowerCase().includes("expired")) return "expired";
    if (msg.toLowerCase().includes("invalid")) return "invalid";
    return "unknown";
  }, [inviteToken, tokenError]);

  // ── Render helpers ────────────────────────────────────────────────────────

  const renderErrorScreen = (kind: TokenErrorKind) => {
    const config: Record<
      TokenErrorKind,
      { icon: React.ReactNode; title: string; body: string }
    > = {
      missing: {
        icon: <AlertCircle className="w-12 h-12 text-amber-400 mx-auto" />,
        title: t("reg_invite_missing_title"),
        body: t("reg_invite_missing_body"),
      },
      invalid: {
        icon: <XCircle className="w-12 h-12 text-red-400 mx-auto" />,
        title: t("reg_invite_invalid_title"),
        body: t("reg_invite_invalid_body"),
      },
      used: {
        icon: <XCircle className="w-12 h-12 text-red-400 mx-auto" />,
        title: t("reg_invite_used_title"),
        body: t("reg_invite_used_body"),
      },
      expired: {
        icon: <Clock className="w-12 h-12 text-amber-400 mx-auto" />,
        title: t("reg_invite_expired_title"),
        body: t("reg_invite_expired_body"),
      },
      unknown: {
        icon: <AlertCircle className="w-12 h-12 text-amber-400 mx-auto" />,
        title: t("reg_invite_invalid_title"),
        body: t("reg_invite_invalid_body"),
      },
    };
    const { icon, title, body } = config[kind];
    return (
      <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-2xl p-8 text-center space-y-4">
        {icon}
        <h2 className="text-white font-bold text-xl">{title}</h2>
        <p className="text-white/70 text-sm leading-relaxed">{body}</p>
        <Button
          variant="ghost"
          className="text-white/60 hover:text-white mt-2"
          onClick={() => (window.location.href = "/login")}
        >
          {t("reg_invite_back_to_login")}
        </Button>
      </div>
    );
  };

  return (
    <div className="relative min-h-screen w-full flex items-center justify-center overflow-hidden">
      {/* Full-screen background */}
      <div
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url(${bgImage})` }}
      />
      <div className="absolute inset-0 bg-black/55" />

      {/* Language selector — top right */}
      <div className="absolute top-4 right-4 z-20">
        <div className="relative">
          <Button
            variant="ghost"
            size="sm"
            className="text-white/80 hover:text-white hover:bg-white/10 gap-1.5"
            onClick={() => setShowLangMenu((v) => !v)}
          >
            <Globe className="w-4 h-4" />
            {LANG_OPTIONS.find((l) => l.code === lang)?.label ?? "Language"}
          </Button>
          {showLangMenu && (
            <div className="absolute right-0 mt-1 w-36 rounded-lg bg-white/95 backdrop-blur shadow-lg border border-gray-200 overflow-hidden z-30">
              {LANG_OPTIONS.map((opt) => (
                <button
                  key={opt.code}
                  className={`w-full text-left px-4 py-2 text-sm hover:bg-gray-100 transition-colors ${
                    lang === opt.code ? "font-semibold text-red-600" : "text-gray-700"
                  }`}
                  onClick={() => {
                    setLang(opt.code as "en" | "es" | "ca");
                    setShowLangMenu(false);
                  }}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Card */}
      <div className="relative z-10 w-full max-w-md mx-4">
        {/* SEBA logo / title */}
        <div className="text-center mb-8">
          <div className="flex justify-center mb-3">
            <img
              src="https://d2xsxph8kpxj0f.cloudfront.net/310419663032477713/ZdUr4NNhMJ6HJrxx9nW6jZ/seba-logo-dark-Bxgq2SHvBzBLRLJPNdvmwf.png"
              alt="SEBA"
              className="h-16 w-auto object-contain drop-shadow-lg"
            />
          </div>
          <p className="text-white/70 text-sm">{t("reg_invite_page_subtitle")}</p>
        </div>

        {/* ── Loading state ── */}
        {tokenLoading && (
          <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-2xl p-10 flex flex-col items-center gap-4">
            <Loader2 className="w-8 h-8 text-white animate-spin" />
            <p className="text-white/70 text-sm">{t("reg_invite_verifying")}</p>
          </div>
        )}

        {/* ── No token in URL ── */}
        {!tokenLoading && !inviteToken && renderErrorScreen("missing")}

        {/* ── Token error ── */}
        {!tokenLoading && inviteToken && tokenError && renderErrorScreen(tokenErrorKind)}

        {/* ── Success / already registered ── */}
        {!tokenLoading && registered && (
          <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-2xl p-8 text-center space-y-4">
            <CheckCircle2 className="w-12 h-12 text-green-400 mx-auto" />
            <h2 className="text-white font-bold text-xl">{t("reg_invite_success_title")}</h2>
            <p className="text-white/70 text-sm">{t("reg_invite_success_body")}</p>
          </div>
        )}

        {/* ── Registration form (only when token is valid) ── */}
        {!tokenLoading && !tokenError && tokenData?.valid && !registered && (
          <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-2xl overflow-hidden">
            <div className="px-6 pt-6 pb-2 border-b border-white/15">
              <h2 className="text-white font-bold text-lg">{t("reg_invite_form_title")}</h2>

              {/* Extra line between title and inputs (per design requirement) */}
              <p className="text-white/60 text-sm mt-1">{t("reg_invite_form_subtitle")}</p>
            </div>

            <form onSubmit={handleRegister} className="p-6 space-y-4">
              <div className="space-y-1.5">
                <Label className="text-white/80 text-sm">{t("local_auth_display_name")}</Label>
                <Input
                  type="text"
                  autoComplete="name"
                  value={regName}
                  onChange={(e) => setRegName(e.target.value)}
                  required
                  className="bg-white/10 border-white/25 text-white placeholder:text-white/40 focus:border-white/60"
                  placeholder={t("local_auth_display_name_placeholder")}
                />
              </div>

              <div className="space-y-1.5">
                <Label className="text-white/80 text-sm">{t("local_auth_email")}</Label>
                <Input
                  type="email"
                  autoComplete="email"
                  value={regEmail}
                  onChange={(e) => setRegEmail(e.target.value)}
                  required
                  // Lock the email field when the invite was issued for a specific address
                  readOnly={!!tokenData.email}
                  className={`bg-white/10 border-white/25 text-white placeholder:text-white/40 focus:border-white/60 ${
                    tokenData.email ? "opacity-70 cursor-not-allowed" : ""
                  }`}
                  placeholder="teacher@escola.cat"
                />
                {tokenData.email && (
                  <p className="text-white/40 text-xs">{t("reg_invite_email_locked")}</p>
                )}
              </div>

              <div className="space-y-1.5">
                <Label className="text-white/80 text-sm">{t("local_auth_password")}</Label>
                <div className="relative">
                  <Input
                    type={showPw ? "text" : "password"}
                    autoComplete="new-password"
                    value={regPassword}
                    onChange={(e) => setRegPassword(e.target.value)}
                    required
                    minLength={8}
                    className="bg-white/10 border-white/25 text-white placeholder:text-white/40 focus:border-white/60 pr-10"
                    placeholder="••••••••"
                  />
                  <button
                    type="button"
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-white/50 hover:text-white/80"
                    onClick={() => setShowPw((v) => !v)}
                  >
                    {showPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
                <p className="text-white/40 text-xs">{t("local_auth_password_hint")}</p>
              </div>

              <div className="space-y-1.5">
                <Label className="text-white/80 text-sm">{t("local_auth_confirm_password")}</Label>
                <Input
                  type={showPw ? "text" : "password"}
                  autoComplete="new-password"
                  value={regConfirm}
                  onChange={(e) => setRegConfirm(e.target.value)}
                  required
                  className="bg-white/10 border-white/25 text-white placeholder:text-white/40 focus:border-white/60"
                  placeholder="••••••••"
                />
              </div>

              {regError && (
                <p className="text-red-300 text-sm bg-red-900/30 border border-red-500/30 rounded-lg px-3 py-2">
                  {regError}
                </p>
              )}

              <Button
                type="submit"
                disabled={registerMutation.isPending}
                className="w-full bg-red-600 hover:bg-red-700 text-white font-semibold h-11 mt-2"
              >
                {registerMutation.isPending ? (
                  <><Loader2 className="w-4 h-4 animate-spin mr-2" />{t("local_auth_creating")}</>
                ) : (
                  t("reg_invite_submit_btn")
                )}
              </Button>
            </form>
          </div>
        )}

        {/* Sovereignty notice */}
        <p className="text-center text-white/40 text-xs mt-6 flex items-center justify-center gap-1.5">
          <ShieldCheck className="w-3.5 h-3.5" />
          {t("local_auth_sovereignty_notice")}
        </p>
      </div>
    </div>
  );
}
