path = "/home/ubuntu/seba-ai-studio/client/src/pages/AdminUserManagement.tsx"
with open(path, "r") as f:
    content = f.read()

# 1. Add MailPlus, RefreshCw, Clock to lucide imports
old_lucide = '  Trash2,\n} from "lucide-react";'
new_lucide = '  Trash2,\n  MailPlus,\n  RefreshCw,\n  Clock,\n} from "lucide-react";'
content = content.replace(old_lucide, new_lucide, 1)

# 2. Add InviteCountdown import
old_import_end = 'import { toast } from "sonner";'
new_import_end = (
    'import { toast } from "sonner";\n'
    'import { InviteCountdown } from "@/components/InviteCountdown";'
)
content = content.replace(old_import_end, new_import_end, 1)

# 3. Add InviteRow type before the Helpers comment
old_type_end = '// ── Helpers ───────────────────────────────────────────────────────────────────'
new_type_end = (
    'type InviteRow = {\n'
    '  id: number;\n'
    '  token: string;\n'
    '  email: string | null;\n'
    '  createdAt: Date | string;\n'
    '  expiresAt: Date | string;\n'
    '  usedAt: Date | string | null;\n'
    '  status: "pending" | "used" | "expired";\n'
    '};\n'
    '// ── Helpers ───────────────────────────────────────────────────────────────────'
)
content = content.replace(old_type_end, new_type_end, 1)

# 4. Add invite state and queries after deleteMutation block
old_after_delete = (
    '  // Filter users\n'
    '  const filtered = useMemo(() => {'
)
new_after_delete = (
    '  // Invite history state\n'
    '  const [confirmDeleteInvite, setConfirmDeleteInvite] = useState<InviteRow | null>(null);\n'
    '  const [confirmResend, setConfirmResend] = useState<InviteRow | null>(null);\n'
    '  const { data: invites = [], isLoading: invitesLoading, refetch: refetchInvites } =\n'
    '    trpc.director.listTeacherInvites.useQuery();\n'
    '  const deleteInviteMutation = trpc.director.deleteTeacherInvite.useMutation({\n'
    '    onSuccess: (data) => {\n'
    '      toast.success(`Invite for ${data.deletedEmail ?? "user"} deleted.`);\n'
    '      setConfirmDeleteInvite(null);\n'
    '      refetchInvites();\n'
    '    },\n'
    '    onError: (err) => toast.error(err.message),\n'
    '  });\n'
    '  const resendMutation = trpc.director.resendTeacherInvite.useMutation({\n'
    '    onSuccess: () => {\n'
    '      toast.success("Invite resent successfully.");\n'
    '      setConfirmResend(null);\n'
    '      refetchInvites();\n'
    '    },\n'
    '    onError: (err) => toast.error(err.message),\n'
    '  });\n'
    '  // Filter users\n'
    '  const filtered = useMemo(() => {'
)
content = content.replace(old_after_delete, new_after_delete, 1)

# 5. Insert Invite History card + dialogs before Powered by SEBA
old_powered = '      {/* Powered by SEBA */}\n      <p className="text-center text-xs text-muted-foreground pt-4">Powered by SEBA</p>'
new_powered = (
    '      {/* Invite History Card */}\n'
    '      <Card className="mt-6">\n'
    '        <CardHeader className="pb-2">\n'
    '          <CardTitle className="text-base font-semibold flex items-center gap-2">\n'
    '            <MailPlus className="h-4 w-4 text-muted-foreground" />\n'
    '            Invite History ({invites.length})\n'
    '          </CardTitle>\n'
    '        </CardHeader>\n'
    '        <CardContent className="p-0">\n'
    '          {invitesLoading ? (\n'
    '            <div className="flex items-center justify-center py-12 text-muted-foreground gap-2">\n'
    '              <Loader2 className="h-5 w-5 animate-spin" />\n'
    '            </div>\n'
    '          ) : invites.length === 0 ? (\n'
    '            <div className="flex flex-col items-center justify-center py-12 text-muted-foreground gap-2">\n'
    '              <MailPlus className="h-8 w-8 opacity-30" />\n'
    '              <p className="text-sm">No invites sent yet.</p>\n'
    '            </div>\n'
    '          ) : (\n'
    '            <div className="overflow-x-auto">\n'
    '              <table className="w-full text-sm">\n'
    '                <thead>\n'
    '                  <tr className="border-b bg-muted/40">\n'
    '                    <th className="text-left px-4 py-3 font-medium text-muted-foreground">Email</th>\n'
    '                    <th className="text-left px-4 py-3 font-medium text-muted-foreground">Status</th>\n'
    '                    <th className="text-left px-4 py-3 font-medium text-muted-foreground">Created</th>\n'
    '                    <th className="text-left px-4 py-3 font-medium text-muted-foreground">Expires</th>\n'
    '                    <th className="text-right px-4 py-3 font-medium text-muted-foreground">Actions</th>\n'
    '                  </tr>\n'
    '                </thead>\n'
    '                <tbody>\n'
    '                  {(invites as InviteRow[]).map((invite) => (\n'
    '                    <tr key={invite.id} className="border-b last:border-0 hover:bg-muted/20 transition-colors">\n'
    '                      <td className="px-4 py-3 text-muted-foreground">{invite.email ?? "—"}</td>\n'
    '                      <td className="px-4 py-3">\n'
    '                        {invite.status === "used" && (\n'
    '                          <Badge variant="outline" className="text-xs text-green-600 border-green-600">Used</Badge>\n'
    '                        )}\n'
    '                        {invite.status === "pending" && (\n'
    '                          <InviteCountdown expiresAt={new Date(invite.expiresAt)} />\n'
    '                        )}\n'
    '                        {invite.status === "expired" && (\n'
    '                          <Badge variant="outline" className="text-xs text-destructive border-destructive">Expired</Badge>\n'
    '                        )}\n'
    '                      </td>\n'
    '                      <td className="px-4 py-3 text-muted-foreground whitespace-nowrap">{formatDate(invite.createdAt as Date)}</td>\n'
    '                      <td className="px-4 py-3 text-muted-foreground whitespace-nowrap">{formatDate(invite.expiresAt as Date)}</td>\n'
    '                      <td className="px-4 py-3">\n'
    '                        <div className="flex justify-end gap-2">\n'
    '                          <Button\n'
    '                            size="sm"\n'
    '                            variant="outline"\n'
    '                            className="gap-1.5"\n'
    '                            disabled={invite.status === "used"}\n'
    '                            onClick={() => setConfirmResend(invite)}\n'
    '                          >\n'
    '                            <RefreshCw className="h-3.5 w-3.5" />\n'
    '                            Resend\n'
    '                          </Button>\n'
    '                          <Button\n'
    '                            size="sm"\n'
    '                            variant="ghost"\n'
    '                            className="gap-1.5 text-destructive hover:text-destructive hover:bg-destructive/10"\n'
    '                            onClick={() => setConfirmDeleteInvite(invite)}\n'
    '                          >\n'
    '                            <Trash2 className="h-3.5 w-3.5" />\n'
    '                            Delete\n'
    '                          </Button>\n'
    '                        </div>\n'
    '                      </td>\n'
    '                    </tr>\n'
    '                  ))}\n'
    '                </tbody>\n'
    '              </table>\n'
    '            </div>\n'
    '          )}\n'
    '        </CardContent>\n'
    '      </Card>\n'
    '      {/* Resend Invite Confirmation */}\n'
    '      {confirmResend && (\n'
    '        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">\n'
    '          <div className="bg-background rounded-xl shadow-2xl p-6 max-w-md w-full mx-4 space-y-4">\n'
    '            <div className="flex items-start gap-3">\n'
    '              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center">\n'
    '                <RefreshCw className="w-5 h-5 text-blue-600" />\n'
    '              </div>\n'
    '              <div>\n'
    '                <h3 className="text-base font-semibold">Resend invite?</h3>\n'
    '                <p className="text-sm text-muted-foreground mt-1">\n'
    '                  Resend the invite link to <span className="font-medium">{confirmResend.email ?? "—"}</span>?\n'
    '                </p>\n'
    '              </div>\n'
    '            </div>\n'
    '            <div className="flex justify-end gap-2">\n'
    '              <Button variant="outline" size="sm" onClick={() => setConfirmResend(null)} disabled={resendMutation.isPending}>Cancel</Button>\n'
    '              <Button size="sm" disabled={resendMutation.isPending}\n'
    '                onClick={() => resendMutation.mutate({ inviteId: confirmResend.id, origin: window.location.origin })}>\n'
    '                {resendMutation.isPending ? <><Loader2 className="w-3 h-3 animate-spin mr-1" />Sending\u2026</> : "Resend"}\n'
    '              </Button>\n'
    '            </div>\n'
    '          </div>\n'
    '        </div>\n'
    '      )}\n'
    '      {/* Delete Invite Confirmation */}\n'
    '      {confirmDeleteInvite && (\n'
    '        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">\n'
    '          <div className="bg-background rounded-xl shadow-2xl p-6 max-w-md w-full mx-4 space-y-4">\n'
    '            <div className="flex items-start gap-3">\n'
    '              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-red-100 flex items-center justify-center">\n'
    '                <Trash2 className="w-5 h-5 text-red-600" />\n'
    '              </div>\n'
    '              <div>\n'
    '                <h3 className="text-base font-semibold">Delete invite?</h3>\n'
    '                <p className="text-sm text-muted-foreground mt-1">\n'
    '                  Permanently delete the invite for <span className="font-medium">{confirmDeleteInvite.email ?? "\u2014"}</span>? This cannot be undone.\n'
    '                </p>\n'
    '              </div>\n'
    '            </div>\n'
    '            <div className="flex justify-end gap-2">\n'
    '              <Button variant="outline" size="sm" onClick={() => setConfirmDeleteInvite(null)} disabled={deleteInviteMutation.isPending}>Cancel</Button>\n'
    '              <Button size="sm" className="bg-red-600 hover:bg-red-700 text-white" disabled={deleteInviteMutation.isPending}\n'
    '                onClick={() => deleteInviteMutation.mutate({ inviteId: confirmDeleteInvite.id })}>\n'
    '                {deleteInviteMutation.isPending ? <><Loader2 className="w-3 h-3 animate-spin mr-1" />Deleting\u2026</> : <><Trash2 className="w-3 h-3 mr-1" />Delete</>}\n'
    '              </Button>\n'
    '            </div>\n'
    '          </div>\n'
    '        </div>\n'
    '      )}\n'
    '      {/* Powered by SEBA */}\n'
    '      <p className="text-center text-xs text-muted-foreground pt-4">Powered by SEBA</p>'
)
content = content.replace(old_powered, new_powered, 1)

with open(path, "w") as f:
    f.write(content)

checks = ["InviteRow", "listTeacherInvites", "deleteTeacherInvite", "resendTeacherInvite", "confirmDeleteInvite", "confirmResend", "InviteCountdown", "MailPlus"]
for c in checks:
    status = "OK" if c in content else "MISSING"
    print(f"  [{status}] {c}")
